CREATE TABLE IF NOT EXISTS economy.wallet (
    wallet_id SERIAL PRIMARY KEY,
    account_id INTEGER NOT NULL UNIQUE,
    balance INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);